source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'SoulSDK_Tests', :exclusive => true do
    pod 'SoulSDK', :path => '../'

    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'

    pod 'AFNetworking', '~> 3.0'
    pod 'EasyMapping', '~> 0.15.0'
end
